// <auto-generated />
using Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250628233822_InvoiceJournal")]
    partial class InvoiceJournal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("accountid");

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("accounttypeid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric")
                        .HasColumnName("balance");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<decimal>("Credit")
                        .HasColumnType("numeric")
                        .HasColumnName("credit");

                    b.Property<decimal>("Debit")
                        .HasColumnType("numeric")
                        .HasColumnName("debit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<decimal>("YearEndBudget")
                        .HasColumnType("numeric")
                        .HasColumnName("yearendbudget");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_accountid");

                    b.HasIndex("AccountTypeId")
                        .HasDatabaseName("ix_accounts_accounttypeid");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Api.Entities.AccountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_accounttypes");

                    b.ToTable("accounttypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Cash",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Bank",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Trade Receivable",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Non-Trade Receivable",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Material",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Inventory",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Properties",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Accumulated Depreciation",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Other Current Assets",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Other Non-Current Assets",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Payable",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Other Current Liabilities",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Other Non-Current Liabilities",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Capital",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Sales",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Sales Discount",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Expenses",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        });
                });

            modelBuilder.Entity("Api.Entities.AccountsPayable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric")
                        .HasColumnName("balance");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<LocalDate?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("duedate");

                    b.Property<int>("JournalEntryId")
                        .HasColumnType("integer")
                        .HasColumnName("journalentryid");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("referencenumber");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("supplierid");

                    b.Property<int?>("Terms")
                        .HasColumnType("integer")
                        .HasColumnName("terms");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("totalamount");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<int>("VoucherNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vouchernumber");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("VoucherNumber"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("VoucherNumber"), 1000L, null, null, null, null, null);

                    b.HasKey("Id")
                        .HasName("pk_accountspayable");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("ix_accountspayable_journalentryid");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_accountspayable_supplierid");

                    b.HasIndex("VoucherNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_accountspayable_vouchernumber");

                    b.ToTable("accountspayable", (string)null);
                });

            modelBuilder.Entity("Api.Entities.CollectionPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("invoiceid");

                    b.Property<int>("JournalEntryId")
                        .HasColumnType("integer")
                        .HasColumnName("journalentryid");

                    b.Property<int>("ReceiptNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("receiptnumber");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ReceiptNumber"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("ReceiptNumber"), 10100L, null, null, null, null, null);

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("text")
                        .HasColumnName("referencenumber");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequencenumber");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_collectionpayment");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_collectionpayment_invoiceid");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("ix_collectionpayment_journalentryid");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_collectionpayment_receiptnumber");

                    b.ToTable("collectionpayment", (string)null);
                });

            modelBuilder.Entity("Api.Entities.CostCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_costcenters");

                    b.ToTable("costcenters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Default Cost Center",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        });
                });

            modelBuilder.Entity("Api.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("numeric")
                        .HasColumnName("creditlimit");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("customerid");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("PaymentTermId")
                        .HasColumnType("integer")
                        .HasColumnName("paymenttermid");

                    b.Property<string>("Tin")
                        .HasColumnType("text")
                        .HasColumnName("tin");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_customerid");

                    b.HasIndex("PaymentTermId")
                        .HasDatabaseName("ix_customers_paymenttermid");

                    b.ToTable("customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            CustomerId = "4000100",
                            Name = "Cash",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        });
                });

            modelBuilder.Entity("Api.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("employeeid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("middlename");

                    b.Property<string>("PagIbigId")
                        .HasColumnType("text")
                        .HasColumnName("pagibigid");

                    b.Property<string>("PhilhealthId")
                        .HasColumnType("text")
                        .HasColumnName("philhealthid");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("numeric")
                        .HasColumnName("rate");

                    b.Property<int>("SalaryUnit")
                        .HasColumnType("integer")
                        .HasColumnName("salaryunit");

                    b.Property<string>("Tin")
                        .HasColumnType("text")
                        .HasColumnName("tin");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_employeeid");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Api.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("itemid");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_inventory");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_inventory_itemid");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("Api.Entities.InventoryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryId")
                        .HasColumnType("integer")
                        .HasColumnName("inventoryid");

                    b.Property<int?>("LineItemId")
                        .HasColumnType("integer")
                        .HasColumnName("lineitemid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("StockAfter")
                        .HasColumnType("integer")
                        .HasColumnName("stockafter");

                    b.Property<int>("StockBefore")
                        .HasColumnType("integer")
                        .HasColumnName("stockbefore");

                    b.Property<Instant>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_inventorylogs");

                    b.HasIndex("InventoryId")
                        .HasDatabaseName("ix_inventorylogs_inventoryid");

                    b.HasIndex("LineItemId")
                        .HasDatabaseName("ix_inventorylogs_lineitemid");

                    b.ToTable("inventorylogs", (string)null);
                });

            modelBuilder.Entity("Api.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customerid");

                    b.Property<decimal>("Discounted")
                        .HasColumnType("numeric")
                        .HasColumnName("discounted");

                    b.Property<decimal?>("InstalmentBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("instalmentbalance");

                    b.Property<int>("JournalEntryId")
                        .HasColumnType("integer")
                        .HasColumnName("journalentryid");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("netamount");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Number"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Number"), 1000L, null, null, null, null, null);

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer")
                        .HasColumnName("paymentmethod");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("vatamount");

                    b.Property<decimal>("VatableAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("vatableamount");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_invoices_customerid");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("ix_invoices_journalentryid");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_invoices_number");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("Api.Entities.InvoiceLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("invoiceid");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("linetotal");

                    b.Property<int>("OriginalItemId")
                        .HasColumnType("integer")
                        .HasColumnName("originalitemid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_invoicelineitems");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_invoicelineitems_invoiceid");

                    b.HasIndex("OriginalItemId")
                        .HasDatabaseName("ix_invoicelineitems_originalitemid");

                    b.ToTable("invoicelineitems", (string)null);
                });

            modelBuilder.Entity("Api.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("code");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<decimal>("Reorder")
                        .HasColumnType("numeric")
                        .HasColumnName("reorder");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("numeric")
                        .HasColumnName("unitcost");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unitprice");

                    b.Property<int>("UomId")
                        .HasColumnType("integer")
                        .HasColumnName("uomid");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<decimal>("Wholesale")
                        .HasColumnType("numeric")
                        .HasColumnName("wholesale");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_items_categoryid");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_items_code");

                    b.HasIndex("UomId")
                        .HasDatabaseName("ix_items_uomid");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("Api.Entities.ItemCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_itemcategories");

                    b.ToTable("itemcategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Electrical",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Office Equipment",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Tools and Equipment",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Motorpool",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Plumbing",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Finishing & Paintings",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Masonry",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Metals",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Woods & Plastics",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Consumables",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Doors & Windows",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Office Supplies",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Furniture & Fixture",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Services",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        });
                });

            modelBuilder.Entity("Api.Entities.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("JournalTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("journaltypeid");

                    b.Property<string>("ReferenceNumber1")
                        .HasColumnType("text")
                        .HasColumnName("referencenumber1");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_journalentries");

                    b.HasIndex("JournalTypeId")
                        .HasDatabaseName("ix_journalentries_journaltypeid");

                    b.ToTable("journalentries", (string)null);
                });

            modelBuilder.Entity("Api.Entities.JournalLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("accountid");

                    b.Property<int?>("CostCenterId")
                        .HasColumnType("integer")
                        .HasColumnName("costcenterid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<decimal?>("Credit")
                        .HasColumnType("numeric")
                        .HasColumnName("credit");

                    b.Property<decimal?>("Debit")
                        .HasColumnType("numeric")
                        .HasColumnName("debit");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("JournalEntryId")
                        .HasColumnType("integer")
                        .HasColumnName("journalentryid");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("linenumber");

                    b.Property<string>("ReferenceNumber1")
                        .HasColumnType("text")
                        .HasColumnName("referencenumber1");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_journallines");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_journallines_accountid");

                    b.HasIndex("CostCenterId")
                        .HasDatabaseName("ix_journallines_costcenterid");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("ix_journallines_journalentryid");

                    b.ToTable("journallines", (string)null);
                });

            modelBuilder.Entity("Api.Entities.JournalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_journaltypes");

                    b.ToTable("journaltypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "General",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Disbursements",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Payables",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Receipts",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Purchases",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Sales",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Production",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Cancelled",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        });
                });

            modelBuilder.Entity("Api.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApvNumber")
                        .HasColumnType("integer")
                        .HasColumnName("apvnumber");

                    b.Property<int?>("ChequeStatus")
                        .HasColumnType("integer")
                        .HasColumnName("chequestatus");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<bool>("IsCheque")
                        .HasColumnType("boolean")
                        .HasColumnName("ischeque");

                    b.Property<int>("JournalEntryId")
                        .HasColumnType("integer")
                        .HasColumnName("journalentryid");

                    b.Property<int>("PayeeId")
                        .HasColumnType("integer")
                        .HasColumnName("payeeid");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("referencenumber");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("totalamount");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<int>("VoucherNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vouchernumber");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("VoucherNumber"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("VoucherNumber"), 10000L, null, null, null, null, null);

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("ix_payments_journalentryid");

                    b.HasIndex("PayeeId")
                        .HasDatabaseName("ix_payments_payeeid");

                    b.HasIndex("VoucherNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_vouchernumber");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Api.Entities.PaymentTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_paymentterms");

                    b.ToTable("paymentterms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Label = "Cash",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Label = "7 days",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Label = "30 Days",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Label = "120 Day",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Label = "COD",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        });
                });

            modelBuilder.Entity("Api.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_number");

                    b.ToTable("projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "Default Project",
                            Number = "DEFP001",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        });
                });

            modelBuilder.Entity("Api.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closedat");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("CreditTo")
                        .HasColumnType("integer")
                        .HasColumnName("creditto");

                    b.Property<int>("DebitTo")
                        .HasColumnType("integer")
                        .HasColumnName("debitto");

                    b.Property<LocalDate>("DeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("deliverydate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("Discounted")
                        .HasColumnType("numeric")
                        .HasColumnName("discounted");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("netamount");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Number"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Number"), 1000L, null, null, null, null, null);

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("projectid");

                    b.Property<string>("RRNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("rrnumber");

                    b.Property<string>("RequisitionNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("requisitionnumber");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("supplierid");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("vatamount");

                    b.Property<decimal>("VatableAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("vatableamount");

                    b.HasKey("Id")
                        .HasName("pk_purchaseorders");

                    b.HasIndex("CreditTo")
                        .HasDatabaseName("ix_purchaseorders_creditto");

                    b.HasIndex("DebitTo")
                        .HasDatabaseName("ix_purchaseorders_debitto");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_purchaseorders_number");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_purchaseorders_projectid");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_purchaseorders_supplierid");

                    b.ToTable("purchaseorders", (string)null);
                });

            modelBuilder.Entity("Api.Entities.PurchaseOrderLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("linetotal");

                    b.Property<int>("OriginalItemId")
                        .HasColumnType("integer")
                        .HasColumnName("originalitemid");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("purchaseorderid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_purchaseorderlineitems");

                    b.HasIndex("OriginalItemId")
                        .HasDatabaseName("ix_purchaseorderlineitems_originalitemid");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("ix_purchaseorderlineitems_purchaseorderid");

                    b.ToTable("purchaseorderlineitems", (string)null);
                });

            modelBuilder.Entity("Api.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("numeric")
                        .HasColumnName("creditlimit");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("PaymentTermId")
                        .HasColumnType("integer")
                        .HasColumnName("paymenttermid");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("supplierid");

                    b.Property<string>("Tin")
                        .HasColumnType("text")
                        .HasColumnName("tin");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.HasIndex("PaymentTermId")
                        .HasDatabaseName("ix_suppliers_paymenttermid");

                    b.HasIndex("SupplierId")
                        .IsUnique()
                        .HasDatabaseName("ix_suppliers_supplierid");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("Api.Entities.UnitOfMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_unitofmeasurements");

                    b.ToTable("unitofmeasurements", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "bag",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "bags",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "bottle",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "box",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "can",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "cu",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "cubic meter",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "dumptruck",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "elf",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "gallon",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "half elf",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "kilo",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "liter",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "meter",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "pad",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "pail",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "pair",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "piece",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "roll",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "sack",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "set",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "tin",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "tube",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L),
                            Name = "unit",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17356896000000000L)
                        });
                });

            modelBuilder.Entity("Api.Entities.VW_ItemEndingCost", b =>
                {
                    b.Property<decimal?>("EndCost")
                        .HasColumnType("numeric")
                        .HasColumnName("endcost");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("itemcode");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("itemname");

                    b.Property<decimal?>("Purchase")
                        .HasColumnType("numeric")
                        .HasColumnName("purchase");

                    b.Property<decimal?>("Sold")
                        .HasColumnType("numeric")
                        .HasColumnName("sold");

                    b.ToTable((string)null);

                    b.ToView("view_endinginventorycost", (string)null);
                });

            modelBuilder.Entity("Api.Entities.Account", b =>
                {
                    b.HasOne("Api.Entities.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_accounttypes_accounttypeid");

                    b.Navigation("AccountType");
                });

            modelBuilder.Entity("Api.Entities.AccountsPayable", b =>
                {
                    b.HasOne("Api.Entities.JournalEntry", "JournalEntry")
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accountspayable_journalentries_journalentryid");

                    b.HasOne("Api.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accountspayable_suppliers_supplierid");

                    b.Navigation("JournalEntry");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Api.Entities.CollectionPayment", b =>
                {
                    b.HasOne("Api.Entities.Invoice", null)
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .HasConstraintName("fk_collectionpayment_invoices_invoiceid");

                    b.HasOne("Api.Entities.JournalEntry", "JournalEntry")
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collectionpayment_journalentries_journalentryid");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("Api.Entities.Customer", b =>
                {
                    b.HasOne("Api.Entities.PaymentTerm", "PaymentTerm")
                        .WithMany()
                        .HasForeignKey("PaymentTermId")
                        .HasConstraintName("fk_customers_paymentterms_paymenttermid");

                    b.OwnsOne("Api.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<int>("CustomerId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .HasColumnType("text")
                                .HasColumnName("address_city");

                            b1.Property<string>("LandlineNumber")
                                .HasColumnType("text")
                                .HasColumnName("address_landlinenumber");

                            b1.Property<string>("MobileNumber")
                                .HasColumnType("text")
                                .HasColumnName("address_mobilenumber");

                            b1.Property<string>("Province")
                                .HasColumnType("text")
                                .HasColumnName("address_province");

                            b1.Property<string>("Street")
                                .HasColumnType("text")
                                .HasColumnName("address_street");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId")
                                .HasConstraintName("fk_customers_customers_id");

                            b1.HasData(
                                new
                                {
                                    CustomerId = 1,
                                    City = "",
                                    LandlineNumber = "",
                                    MobileNumber = "",
                                    Province = "",
                                    Street = ""
                                });
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("PaymentTerm");
                });

            modelBuilder.Entity("Api.Entities.Employee", b =>
                {
                    b.OwnsOne("Api.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .HasColumnType("text")
                                .HasColumnName("address_city");

                            b1.Property<string>("LandlineNumber")
                                .HasColumnType("text")
                                .HasColumnName("address_landlinenumber");

                            b1.Property<string>("MobileNumber")
                                .HasColumnType("text")
                                .HasColumnName("address_mobilenumber");

                            b1.Property<string>("Province")
                                .HasColumnType("text")
                                .HasColumnName("address_province");

                            b1.Property<string>("Street")
                                .HasColumnType("text")
                                .HasColumnName("address_street");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId")
                                .HasConstraintName("fk_employees_employees_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Entities.Inventory", b =>
                {
                    b.HasOne("Api.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_items_itemid");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Api.Entities.InventoryLog", b =>
                {
                    b.HasOne("Api.Entities.Inventory", "Inventory")
                        .WithMany("Logs")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventorylogs_inventory_inventoryid");

                    b.HasOne("Api.Entities.PurchaseOrderLineItem", "LineItem")
                        .WithMany()
                        .HasForeignKey("LineItemId")
                        .HasConstraintName("fk_inventorylogs_purchaseorderlineitems_lineitemid");

                    b.Navigation("Inventory");

                    b.Navigation("LineItem");
                });

            modelBuilder.Entity("Api.Entities.Invoice", b =>
                {
                    b.HasOne("Api.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_customers_customerid");

                    b.HasOne("Api.Entities.JournalEntry", "JournalEntry")
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_journalentries_journalentryid");

                    b.Navigation("Customer");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("Api.Entities.InvoiceLineItem", b =>
                {
                    b.HasOne("Api.Entities.Invoice", null)
                        .WithMany("LineItems")
                        .HasForeignKey("InvoiceId")
                        .HasConstraintName("fk_invoicelineitems_invoices_invoiceid");

                    b.HasOne("Api.Entities.Item", "OriginalItem")
                        .WithMany()
                        .HasForeignKey("OriginalItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoicelineitems_items_originalitemid");

                    b.OwnsOne("Api.Entities.ItemSnapshot", "ItemSnapshot", b1 =>
                        {
                            b1.Property<int>("InvoiceLineItemId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(25)
                                .HasColumnType("character varying(25)")
                                .HasColumnName("itemsnapshot_code");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("itemsnapshot_name");

                            b1.Property<decimal>("UnitCost")
                                .HasColumnType("numeric")
                                .HasColumnName("itemsnapshot_unitcost");

                            b1.Property<string>("UnitOfMeasurement")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("itemsnapshot_unitofmeasurement");

                            b1.Property<int>("UnitOfMeasurementId")
                                .HasColumnType("integer")
                                .HasColumnName("itemsnapshot_unitofmeasurementid");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("numeric")
                                .HasColumnName("itemsnapshot_unitprice");

                            b1.HasKey("InvoiceLineItemId");

                            b1.ToTable("invoicelineitems");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceLineItemId")
                                .HasConstraintName("fk_invoicelineitems_invoicelineitems_id");
                        });

                    b.Navigation("ItemSnapshot")
                        .IsRequired();

                    b.Navigation("OriginalItem");
                });

            modelBuilder.Entity("Api.Entities.Item", b =>
                {
                    b.HasOne("Api.Entities.ItemCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_items_itemcategories_categoryid");

                    b.HasOne("Api.Entities.UnitOfMeasurement", "Uom")
                        .WithMany()
                        .HasForeignKey("UomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_items_unitofmeasurements_uomid");

                    b.Navigation("Category");

                    b.Navigation("Uom");
                });

            modelBuilder.Entity("Api.Entities.JournalEntry", b =>
                {
                    b.HasOne("Api.Entities.JournalType", "JournalType")
                        .WithMany()
                        .HasForeignKey("JournalTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_journalentries_journaltypes_journaltypeid");

                    b.Navigation("JournalType");
                });

            modelBuilder.Entity("Api.Entities.JournalLine", b =>
                {
                    b.HasOne("Api.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_journallines_accounts_accountid");

                    b.HasOne("Api.Entities.CostCenter", "CostCenter")
                        .WithMany()
                        .HasForeignKey("CostCenterId")
                        .HasConstraintName("fk_journallines_costcenters_costcenterid");

                    b.HasOne("Api.Entities.JournalEntry", null)
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_journallines_journalentries_journalentryid");

                    b.Navigation("Account");

                    b.Navigation("CostCenter");
                });

            modelBuilder.Entity("Api.Entities.Payment", b =>
                {
                    b.HasOne("Api.Entities.JournalEntry", "JournalEntry")
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_journalentries_journalentryid");

                    b.HasOne("Api.Entities.Supplier", "Payee")
                        .WithMany()
                        .HasForeignKey("PayeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_suppliers_payeeid");

                    b.Navigation("JournalEntry");

                    b.Navigation("Payee");
                });

            modelBuilder.Entity("Api.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("Api.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("CreditTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchaseorders_accounts_creditto");

                    b.HasOne("Api.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("DebitTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchaseorders_accounts_debitto");

                    b.HasOne("Api.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchaseorders_projects_projectid");

                    b.HasOne("Api.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchaseorders_suppliers_supplierid");

                    b.Navigation("Project");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Api.Entities.PurchaseOrderLineItem", b =>
                {
                    b.HasOne("Api.Entities.Item", "OriginalItem")
                        .WithMany()
                        .HasForeignKey("OriginalItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchaseorderlineitems_items_originalitemid");

                    b.HasOne("Api.Entities.PurchaseOrder", null)
                        .WithMany("LineItems")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchaseorderlineitems_purchaseorders_purchaseorderid");

                    b.OwnsOne("Api.Entities.ItemSnapshot", "ItemSnapshot", b1 =>
                        {
                            b1.Property<int>("PurchaseOrderLineItemId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(25)
                                .HasColumnType("character varying(25)")
                                .HasColumnName("itemsnapshot_code");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("itemsnapshot_name");

                            b1.Property<decimal>("UnitCost")
                                .HasColumnType("numeric")
                                .HasColumnName("itemsnapshot_unitcost");

                            b1.Property<string>("UnitOfMeasurement")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("itemsnapshot_unitofmeasurement");

                            b1.Property<int>("UnitOfMeasurementId")
                                .HasColumnType("integer")
                                .HasColumnName("itemsnapshot_unitofmeasurementid");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("numeric")
                                .HasColumnName("itemsnapshot_unitprice");

                            b1.HasKey("PurchaseOrderLineItemId");

                            b1.ToTable("purchaseorderlineitems");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderLineItemId")
                                .HasConstraintName("fk_purchaseorderlineitems_purchaseorderlineitems_id");
                        });

                    b.Navigation("ItemSnapshot")
                        .IsRequired();

                    b.Navigation("OriginalItem");
                });

            modelBuilder.Entity("Api.Entities.Supplier", b =>
                {
                    b.HasOne("Api.Entities.PaymentTerm", "PaymentTerm")
                        .WithMany()
                        .HasForeignKey("PaymentTermId")
                        .HasConstraintName("fk_suppliers_paymentterms_paymenttermid");

                    b.OwnsOne("Api.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<int>("SupplierId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .HasColumnType("text")
                                .HasColumnName("address_city");

                            b1.Property<string>("LandlineNumber")
                                .HasColumnType("text")
                                .HasColumnName("address_landlinenumber");

                            b1.Property<string>("MobileNumber")
                                .HasColumnType("text")
                                .HasColumnName("address_mobilenumber");

                            b1.Property<string>("Province")
                                .HasColumnType("text")
                                .HasColumnName("address_province");

                            b1.Property<string>("Street")
                                .HasColumnType("text")
                                .HasColumnName("address_street");

                            b1.HasKey("SupplierId");

                            b1.ToTable("suppliers");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId")
                                .HasConstraintName("fk_suppliers_suppliers_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("PaymentTerm");
                });

            modelBuilder.Entity("Api.Entities.Inventory", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("Api.Entities.Invoice", b =>
                {
                    b.Navigation("LineItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Api.Entities.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Api.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
